name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Check Gradle Wrapper
        run: ls -la
        working-directory: android # Nếu project có thư mục con 'android'

      - name: Build APK
        run: |
          cd android # Nếu project có thư mục con 'android'
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: android/app/build/outputs/apk/release/*.apk # Đảm bảo đường dẫn đúng
